### ISSUE TITLE
Error with Redmine 2.4

### ISSUE THREAD

**Issue by acosonic** [trappist/redmine_group_watchers#1]
Installed with trouble, replaced 
gem 'deface', :git => 'git://github.com/spree/deface.git'

with

gem 'deface', '1.0.0'
#, :git => 'git://github.com/spree/deface.git'

Also tried with 0.9.0 but

always ended up with below error:

Rendered attachments/_form.html.erb (1.5ms)
  Group Load (0.7ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('Group') ORDER BY users.lastname ASC
Deface: 1 overrides found for 'issues/new'
Deface: 'rewrite_checkboxes' matched 1 times with 'p#watchers_form'
Deface: [WARNING] No :original defined for 'rewrite_checkboxes', you should change its definition to include:
 :original => '5f4825cd12fa092706b1eb55a194181a4fcebdc4' 
  Rendered issues/new.html.erb within layouts/base (80.7ms)
Completed 500 Internal Server Error in 117.3ms

ActionView::Template::Error (uninitialized constant Issue::GroupWatcher):
    37: <p id="group_watchers_form">
    38:   <label><%= l(:label_issue_group_watchers) %></label>
    39:   <span id="group_watchers_inputs">
    40:     <%= watchers_checkboxes(@issue, Group.sorted.all - @issue.group_watchers.all) %>
    41:   </span>
    42:   <br>
    43:   <span class="search_for_watchers">
  app/views/issues/new.html.erb:40:in `block in _ba8c5d6b4c6b57e26f28e0ffd2e7a502'
  app/helpers/application_helper.rb:977:in `labelled_form_for'
  app/views/issues/new.html.erb:5:in `_ba8c5d6b4c6b57e26f28e0ffd2e7a502'
  app/controllers/issues_controller.rb:139:in `block (2 levels) in new'
  app/controllers/issues_controller.rb:138:in `new'

**Comment by trappist** [comment]
Hi @acosonic this plugin is 4 years old, probably would need an overhaul to work with modern Redmine.

**Comment by acosonic** [comment]
I am trying to use it with old redmine version.

Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-darwin15.6.0]
  Rails version                  3.2.16
  Environment                    development
  Database adapter               Mysql2
